services:
  postgres:
    image: postgres:16-alpine
    container_name: travel-app-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: travel_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev']
      interval: 10s
      timeout: 5s
      retries: 5

  inbucket:
    image: inbucket/inbucket:latest
    container_name: travel-app-inbucket
    restart: unless-stopped
    ports:
      - '9000:9000' # Web UI
      - '2500:2500' # SMTP
      - '1100:1100' # POP3
    environment:
      INBUCKET_SMTP_ADDR: '0.0.0.0:2500'
      INBUCKET_WEB_ADDR: '0.0.0.0:9000'

volumes:
  postgres_data:
    driver: local
